### ISSUE TITLE
package "android/soong/generator" already has a package context

### ISSUE THREAD

**Issue by wowufoundme** [Cosmic-OS/platform_manifest#29]
Any idea how to resolve this? Searched everywhere on the internet still can't find anything

```
Building Cosmic OS $(COS_VERSION_NUMBER)-$(COS_CODENAME)-$(COS_BUILD_TYPE) for enchilada
Start time: Sat Jun 15 23:02:15 IST 2019

Setting up the environment

including device/google/crosshatch/vendorsetup.sh
including device/oneplus/enchilada/vendorsetup.sh
including vendor/cos/sdclang/vendorsetup.sh
including vendor/cos/vendorsetup.sh
including vendor/lineage/vendorsetup.sh
including sdk/bash_completion/adb.bash

Lunching enchilada (Including dependencies sync)


============================================
COS_VERSION=Cosmic-OS_Corona_enchilada_9.0_20190615_4.0-UNOFFICIAL
TARGET_BUILD_VARIANT=userdebug
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a75
BUILD_ID=PQ2A.190305.002
============================================

Starting compilation

============================================
COS_VERSION=Cosmic-OS_Corona_enchilada_9.0_20190615_4.0-UNOFFICIAL
TARGET_BUILD_VARIANT=userdebug
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a75
BUILD_ID=PQ2A.190305.002
============================================
[1/1] /home/shubhkirti/WORKSPACE/cosmic/out/soong/.minibootstrap/minibp /home/shubhkirti/WORKSPACE/cosmic/out/soong/.bootstrap/build.ninja
[55/56] glob prebuilts/ndk/stl.bp
[63/81] test android/soong/cc/config
[79/81] test android/soong/cc
[81/81] /home/shubhkirti/WORKSPACE/cosmic/out/soong/.bootstrap/bin/soong_build /home/shubhkirti/WORKSPACE/cosmic/out/soong/build.ninja
FAILED: /home/shubhkirti/WORKSPACE/cosmic/out/soong/build.ninja 
/home/shubhkirti/WORKSPACE/cosmic/out/soong/.bootstrap/bin/soong_build -t -l /home/shubhkirti/WORKSPACE/cosmic/out/.module_paths/Android.bp.list -b /home/shubhkirti/WORKSPACE/cosmic/out/soong -n /home/shubhkirti/WORKSPACE/cosmic/out -d /home/shubhkirti/WORKSPACE/cosmic/out/soong/build.ninja.d -o /home/shubhkirti/WORKSPACE/cosmic/out/soong/build.ninja Android.bp
(0x902b80,0xc42010a8d0)panic: package "android/soong/generator" already has a package context

goroutine 1 [running]:
github.com/google/blueprint.NewPackageContext(0x8a7bbf, 0x17, 0x8aebc8, 0x21)
	/home/shubhkirti/WORKSPACE/cosmic/build/blueprint/package_ctx.go:99 +0x464
android/soong/android.NewPackageContext(0x8a7bbf, 0x17, 0xc4200b7f68, 0x797abe)
	/home/shubhkirti/WORKSPACE/cosmic/build/soong/android/package_ctx.go:33 +0x35

```

**Comment by Sid-Sun** [comment]
@wowufoundme Won't fix, JK

**Comment by shivamdev-lgtm** [comment]
Cosmic ded boi

**Comment by wowufoundme** [comment]
@Sid-Sun 
> @wowufoundme Won't fix, JK

Does this mean I have to repo init and sync again?

**Comment by wowufoundme** [comment]
Fixed it by running `make clean` and then `repo sync --no-clone-bundle`, deleting the whole directory.

**Comment by Mikdadali** [comment]
how to fix this?

![Screenshot_20200414-212629](https://user-images.githubusercontent.com/10883393/79246674-212d4d80-7e97-11ea-8c08-7c6baadc44c3.jpg)

**Comment by sagarshah1729** [comment]
> how to fix this?
> 
> ![Screenshot_20200414-212629](https://user-images.githubusercontent.com/10883393/79246674-212d4d80-7e97-11ea-8c08-7c6baadc44c3.jpg)

I guess you have a duplicate vendor cloned in your build system. Also, is it Cosmic-OS?
